name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: ./.github/actions/build-native

  build-macos:
    strategy:
      matrix:
        runner: [macos-15, macos-15-intel]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: ./.github/actions/build-native

  build-windows:
    strategy:
      matrix:
        runner: [windows-2025, windows-11-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: ./.github/actions/build-native

  build-android:
    strategy:
      matrix:
        include:
          - abi: armeabi-v7a
            preset: android-armv7
          - abi: arm64-v8a
            preset: android-arm64
          - abi: x86_64
            preset: android-x64
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: ./.github/actions/build-android
        with:
          abi: ${{ matrix.abi }}
          preset: ${{ matrix.preset }}

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: ./.github/actions/build-ios
